/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JCheckBox;

/**
 *
 * @author Gabriel
 */
public class BootcampSubscribe_GUI extends javax.swing.JFrame {

    /**
     * Creates new form BootcampSubscribe_btn
     */
    private List<JCheckBox> bootcamps; 
    public BootcampSubscribe_GUI() {
        initComponents();
        bootcamp1_box.setText(main.Main.bootcamp1.getName());
        bootcamp2_box.setText(main.Main.bootcamp2.getName());
        this.bootcamps = new ArrayList<>();
        bootcamps.add(bootcamp1_box);
        bootcamps.add(bootcamp2_box);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        bootcamp1_box = new javax.swing.JCheckBox();
        bootcamp2_box = new javax.swing.JCheckBox();
        subscribe_btn = new javax.swing.JButton();
        back_btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(null);

        bootcamp1_box.setText("jCheckBox1");
        jPanel1.add(bootcamp1_box);
        bootcamp1_box.setBounds(150, 90, 250, 40);

        bootcamp2_box.setText("jCheckBox2");
        jPanel1.add(bootcamp2_box);
        bootcamp2_box.setBounds(150, 150, 250, 24);

        subscribe_btn.setText("Subscribe");
        subscribe_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subscribe_btnActionPerformed(evt);
            }
        });
        jPanel1.add(subscribe_btn);
        subscribe_btn.setBounds(150, 240, 100, 32);

        back_btn.setText("Back");
        back_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_btnActionPerformed(evt);
            }
        });
        jPanel1.add(back_btn);
        back_btn.setBounds(330, 0, 70, 50);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(400, 300));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void subscribe_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subscribe_btnActionPerformed
        if(bootcamp1_box.isSelected() && !main.Main.bootcamp1.getEnrolledDevs().contains(Index_GUI.client)) {
            main.Main.bootcamp1.getEnrolledDevs().add(Index_GUI.client);
            Index_GUI.client.getEnrolledContents().addAll(main.Main.bootcamp1.getContents());
        }

        if(bootcamp2_box.isSelected() && !main.Main.bootcamp2.getEnrolledDevs().contains(Index_GUI.client)) {
            main.Main.bootcamp2.getEnrolledDevs().add(Index_GUI.client);
            Index_GUI.client.getEnrolledContents().addAll(main.Main.bootcamp2.getContents());
        }
    }//GEN-LAST:event_subscribe_btnActionPerformed

    private void back_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_btnActionPerformed
        dispose();
        new DevMenu_GUI().setVisible(true);
    }//GEN-LAST:event_back_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BootcampSubscribe_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BootcampSubscribe_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BootcampSubscribe_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BootcampSubscribe_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BootcampSubscribe_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back_btn;
    private javax.swing.JCheckBox bootcamp1_box;
    private javax.swing.JCheckBox bootcamp2_box;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton subscribe_btn;
    // End of variables declaration//GEN-END:variables
}
