/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JOptionPane;

/**
 *
 * @author Gabriel
 */
public class EnrolledBootcamps_GUI extends javax.swing.JFrame {

    /**
     * Creates new form EnrolledBootcamps_GUI
     */
    public static boolean con;
    public EnrolledBootcamps_GUI() {
        initComponents();
        bootcamp1_btn.setText(main.Main.bootcamp1.getName());
        bootcamp2_btn.setText(main.Main.bootcamp2.getName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bootcamp1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        bootcamp1_btn = new javax.swing.JButton();
        bootcamp2_btn = new javax.swing.JButton();
        back_btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        bootcamp1.setLayout(null);

        jLabel1.setText("Enrolled Bootcamps");
        bootcamp1.add(jLabel1);
        jLabel1.setBounds(140, 20, 120, 16);

        bootcamp1_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bootcamp1_btnActionPerformed(evt);
            }
        });
        bootcamp1.add(bootcamp1_btn);
        bootcamp1_btn.setBounds(50, 110, 320, 40);

        bootcamp2_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bootcamp2_btnActionPerformed(evt);
            }
        });
        bootcamp1.add(bootcamp2_btn);
        bootcamp2_btn.setBounds(50, 180, 320, 40);

        back_btn.setText("back");
        back_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_btnActionPerformed(evt);
            }
        });
        bootcamp1.add(back_btn);
        back_btn.setBounds(320, 0, 58, 60);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bootcamp1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bootcamp1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(400, 300));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bootcamp1_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bootcamp1_btnActionPerformed
        if(main.Main.bootcamp1.getEnrolledDevs().contains(Index_GUI.client)) {
            if(Index_GUI.client.getEnrolledContents().size() == 0) {
                JOptionPane.showMessageDialog(null, "You have already completed the bootcamp!");
                return;
            }
            con = true;
            dispose();
            new BootcampContents_GUI().setVisible(true);
        }
        else {
        JOptionPane.showMessageDialog(null, "You are not subscribed in this bootcamp");
        }
    }//GEN-LAST:event_bootcamp1_btnActionPerformed

    private void bootcamp2_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bootcamp2_btnActionPerformed
        if(main.Main.bootcamp2.getEnrolledDevs().contains(Index_GUI.client)) {
            if(Index_GUI.client.getEnrolledContents().size() == 0) {
                JOptionPane.showMessageDialog(null, "You have already completed the bootcamp!");
                return;
            }
            con = false;
            dispose();
            new BootcampContents_GUI().setVisible(true);
        }
        else {
        JOptionPane.showMessageDialog(null, "You are not subscribed in this bootcamp");
        }
    }//GEN-LAST:event_bootcamp2_btnActionPerformed

    private void back_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_btnActionPerformed
        dispose();
        new DevMenu_GUI().setVisible(true);
    }//GEN-LAST:event_back_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EnrolledBootcamps_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EnrolledBootcamps_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EnrolledBootcamps_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EnrolledBootcamps_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EnrolledBootcamps_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back_btn;
    private javax.swing.JPanel bootcamp1;
    private javax.swing.JButton bootcamp1_btn;
    private javax.swing.JButton bootcamp2_btn;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
